export const LANDING = "/";
export const SIGN_IN = "/signin";
export const SIGN_UP = "/signup";
export const GAME_PLAY = "/gameplay";
// export const SIGN_UP = '/signup';
// export const HOME = '/home';
// export const ACCOUNT = '/account';
// export const ADMIN = '/admin';
// export const PASSWORD_FORGET = '/pw-forget';
